/**
 * Emits src/tokens/tokens.css from the TypeScript token source.
 *
 *   bun run tokens
 *
 * The generated file is committed so consumers (and the Tauri webview) get
 * plain CSS with no build step. Re-run after editing anything in
 * src/tokens/*.ts.
 */

import { flattenTheme, type ThemeMode } from "../src/tokens/themes.ts";
import { densityTokens } from "../src/tokens/density.ts";
import { tints } from "../src/tokens/tints.ts";
import {
  cadence,
  duration,
  easing,
  focusRing,
  fontFamily,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  measure,
  radius,
  size,
  space,
  spaceNamed,
  zIndex,
} from "../src/tokens/scale.ts";

const PREFIX = "--ds-";

function block(selector: string, vars: Record<string, string>, indent = ""): string {
  const lines = Object.entries(vars).map(([k, v]) => `${indent}  ${PREFIX}${k}: ${v};`);
  return `${indent}${selector} {\n${lines.join("\n")}\n${indent}}`;
}

function staticVars(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(space)) out[`space-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(spaceNamed)) out[`space-${kebab(k)}`] = `${v}px`;
  for (const [k, v] of Object.entries(radius)) out[`radius-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(fontFamily)) out[`font-${k}`] = v;
  for (const [k, v] of Object.entries(fontSize)) out[`text-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(lineHeight)) out[`leading-${k}`] = `${v}`;
  for (const [k, v] of Object.entries(fontWeight)) out[`weight-${k}`] = `${v}`;
  for (const [k, v] of Object.entries(letterSpacing)) out[`tracking-${k}`] = v;
  for (const [k, v] of Object.entries(size)) out[`size-${kebab(k)}`] = `${v}px`;
  for (const [k, v] of Object.entries(duration)) out[`duration-${k}`] = `${v}ms`;
  for (const [k, v] of Object.entries(easing)) out[`ease-${k}`] = v;
  // Live loops divide by --ds-motion-live at the call site; the raw cadence
  // never changes, so reduced motion is a single switch, not N overrides.
  for (const [k, v] of Object.entries(cadence)) out[`cadence-${k}`] = `${v}ms`;
  for (const [k, v] of Object.entries(measure)) out[`measure-${k}`] = v;
  for (const [k, v] of Object.entries(zIndex)) out[`z-${k}`] = `${v}`;
  for (const [k, v] of Object.entries(tints)) out[`tint-${kebab(k)}`] = `${Math.round(v * 1000) / 10}%`;
  // Density tokens with no scale entry (unitless leading, em gaps) still
  // need a :root default for trees that never set data-density.
  for (const [k, v] of Object.entries(densityTokens.comfortable)) if (!(k in out)) out[k] = v;
  out["focus-ring-width"] = `${focusRing.width}px`;
  out["focus-ring-offset"] = `${focusRing.offset}px`;
  return out;
}

function kebab(s: string): string {
  return s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
}

function themeBlock(mode: ThemeMode, selector: string, indent = ""): string {
  return block(selector, { "color-scheme": mode, ...flattenTheme(mode) }, indent).replace(
    `${PREFIX}color-scheme`,
    "color-scheme",
  );
}

/** The full text of tokens.css. */
export function buildTokensCss(): string {
  return `/* GENERATED by scripts/build-tokens.ts — do not edit by hand. */

/* ------------------------------------------------------------------ */
/* Static scales                                                       */
/* ------------------------------------------------------------------ */
${block(":root", staticVars())}

/* ------------------------------------------------------------------ */
/* Themes. Dark is the default; [data-theme] wins over the OS setting. */
/* ------------------------------------------------------------------ */
${themeBlock("dark", ':root, [data-theme="dark"]')}

${themeBlock("light", '[data-theme="light"]')}

@media (prefers-color-scheme: light) {
${themeBlock("light", ':root:not([data-theme="dark"])', "  ")}
}

/* ------------------------------------------------------------------ */
/* Density. Comfortable is the :root default above. Only the tokens in   */
/* src/tokens/density.ts differ; both values are emitted so a subtree    */
/* can switch either way.                                               */
/* ------------------------------------------------------------------ */
${block('[data-density="comfortable"]', densityTokens.comfortable)}

${block('[data-density="compact"]', densityTokens.compact)}

/* ------------------------------------------------------------------ */
/* Motion                                                              */
/* ------------------------------------------------------------------ */

/*
 * The default is declared before the overrides. A :root rule and a :root rule
 * inside a media query have the same specificity, so source order decides:
 * emitting the default last would silently defeat the reduced-motion
 * preference.
 */
:root {
  /* 1 = live indicators may pulse; 0 = they hold still. */
  ${PREFIX}motion-live: 1;
}

@media (prefers-reduced-motion: reduce) {
  :root {
    ${PREFIX}duration-fast: 0ms;
    ${PREFIX}duration-base: 0ms;
    ${PREFIX}duration-slow: 0ms;
    ${PREFIX}duration-deliberate: 0ms;
    ${PREFIX}motion-live: 0;
  }
}

/* Explicit opt-in, for a user toggle that does not touch the OS setting. */
[data-reduced-motion="true"] {
  ${PREFIX}duration-fast: 0ms;
  ${PREFIX}duration-base: 0ms;
  ${PREFIX}duration-slow: 0ms;
  ${PREFIX}duration-deliberate: 0ms;
  ${PREFIX}motion-live: 0;
}
`;
}

export const TOKENS_CSS_URL = new URL("../src/tokens/tokens.css", import.meta.url);

if (import.meta.main) {
  const css = buildTokensCss();
  await Bun.write(TOKENS_CSS_URL, css);
  console.log(`wrote ${TOKENS_CSS_URL.pathname} (${css.length} bytes)`);
}
