export { StatusBadge } from "./StatusBadge.tsx";
export type { StatusBadgeProps } from "./StatusBadge.tsx";
export { NeedsYouCount, StatusMark } from "./StatusMark.tsx";
export type { NeedsYouCountProps, StatusMarkProps } from "./StatusMark.tsx";
export { AuthorLine, PersonAvatar, PersonAvatarStack, PersonLine, personTitle } from "./PersonAvatar.tsx";
export type { AuthorLineProps, Person, PersonAvatarProps, PersonAvatarStackProps, PersonAvatarSize, PersonLineProps } from "./PersonAvatar.tsx";
export { EntityLine } from "./EntityLine.tsx";
export { GitHubFace, GitHubUserLine } from "./GitHubUserLine.tsx";
export type { GitHubUser, GitHubUserLineProps } from "./GitHubUserLine.tsx";
export type { EntityLineProps } from "./EntityLine.tsx";
export { ProjectAvatar } from "./ProjectAvatar.tsx";
export type { ProjectAvatarProps, ProjectFace } from "./ProjectAvatar.tsx";
export { PrChip, PR_DISPLAY_SPECS, prFacts, prSpecOf, prStateOf } from "./PrChip.tsx";
export type { PrChipProps, PrChipPullRequest, PrDisplaySpec } from "./PrChip.tsx";
export { Cost } from "./Cost.tsx";
export type { CostProps } from "./Cost.tsx";
export { MarkdownDocument, highlightMarkdown } from "./MarkdownDocument.tsx";
export type { MarkdownDocumentProps, HighlightKind, HighlightSpan } from "./MarkdownDocument.tsx";
export { AgentAvatar, ROLE_ICON, ROLE_LABEL } from "./AgentAvatar.tsx";
export type { AgentAvatarProps, AvatarKind } from "./AgentAvatar.tsx";
export { CostDisplay, TokenCount, Duration } from "./Numbers.tsx";
export type { CostDisplayProps, TokenCountProps, DurationProps } from "./Numbers.tsx";
export { MetricTile, MetricGroup } from "./MetricTile.tsx";
export type { MetricTileProps, MetricGroupProps, MetricDelta, MetricUnit } from "./MetricTile.tsx";
export { EventRow, EventStream, EventDayDivider } from "./EventRow.tsx";
export type { EventRowProps, EventStreamProps, EventActor, EventSeverity } from "./EventRow.tsx";
export { SessionTreeNode, SessionTree } from "./SessionTreeNode.tsx";
export type { SessionTreeNodeProps, SessionTreeProps, SessionNodeData } from "./SessionTreeNode.tsx";
export { DiffView, DiffFile, parseUnifiedDiff } from "./DiffView.tsx";
export { LiveDiff } from "./LiveDiff.tsx";
export type { LiveDiffProps, LiveDiffFile, LiveDiffHunk, LiveDiffLine, LastChange } from "./LiveDiff.tsx";
export type { DiffViewProps, DiffFileProps, FileDiff, DiffHunk, DiffLine, DiffLineKind, FileChangeKind } from "./DiffView.tsx";
export { LogStream } from "./LogStream.tsx";
export type { LogStreamProps, LogLine, LogLevel, LogChannel } from "./LogStream.tsx";
export { Markdown } from "./Markdown.tsx";
export type { MarkdownProps, MarkdownVariant } from "./Markdown.tsx";
export { ActivityIndicator } from "./ActivityIndicator.tsx";
export type { ActivityIndicatorProps } from "./ActivityIndicator.tsx";
export { AnsiString } from "./AnsiString.tsx";
export type { AnsiStringProps } from "./AnsiString.tsx";
export { ToolCallCard, summarizeToolArgs } from "./ToolCallCard.tsx";
export type { ToolCallCardProps, ToolOutput } from "./ToolCallCard.tsx";
export { ThinkingBlock } from "./ThinkingBlock.tsx";
export type { ThinkingBlockProps } from "./ThinkingBlock.tsx";
export { AgentPlan, PlanMeter, planProgress } from "./AgentPlan.tsx";
export type { AgentPlanProps, PlanItem, PlanMeterProps } from "./AgentPlan.tsx";
export { ChatAside, ChatMessage } from "./ChatMessage.tsx";
export type { ChatMessageProps, ChatMessageKind, HumanIntent } from "./ChatMessage.tsx";
export { ChatThread } from "./ChatThread.tsx";
export type { ChatThreadProps } from "./ChatThread.tsx";
export { ChatTranscript, SessionHeader } from "./ChatTranscript.tsx";
export type { ChatTranscriptProps, ChatTranscriptSession, SessionHeaderProps } from "./ChatTranscript.tsx";
export { QuestionCard } from "./QuestionCard.tsx";
export type { QuestionCardProps, QuestionState, QuestionKind } from "./QuestionCard.tsx";
export { ChatComposer } from "./ChatComposer.tsx";
export type { ChatComposerProps, ComposerMode, ComposerSubmission, PendingQuestion } from "./ChatComposer.tsx";
export { AttachDropZone, AttachmentChip, ImageViewer, MessageImages, attachmentWarning, imageCaption, wasScaled } from "./ImageAttachments.tsx";
export type { AttachDropZoneProps, AttachmentChipProps, ComposerAttachment, ImageFacts, ImageViewerProps, MessageImagesProps, SentImage } from "./ImageAttachments.tsx";
export { NavTree, NavTreeRow, rowLabel } from "./NavTree.tsx";
export type { NavTreeProps, NavTreeRowProps, NavRowMenuControls } from "./NavTree.tsx";
export { Sidebar, SidebarLink, SidebarProfile, SidebarToggle, SIDEBAR_DRAWER_QUERY } from "./Sidebar.tsx";
export type { SidebarProps, SidebarLinkProps, SidebarProfileProps, SidebarToggleProps } from "./Sidebar.tsx";
export { Board } from "./Board.tsx";
export type { BoardProps } from "./Board.tsx";
export { FindingRow, FindingGroup, sortFindings, countFindings, FINDING_SEVERITIES, FINDING_SEVERITY_SPECS, FINDING_STATUSES, FINDING_STATUS_SPECS } from "./FindingRow.tsx";
export type { FindingRowProps, FindingGroupProps, FindingLike, FindingCounts, FindingSeveritySpec, FindingStatusSpec } from "./FindingRow.tsx";
export { Breadcrumb, elideMiddle } from "./Breadcrumb.tsx";
export type { BreadcrumbProps, BreadcrumbItem } from "./Breadcrumb.tsx";
export { ArtifactRow, ArtifactGroup, artifactKind, ARTIFACT_KIND_SPECS } from "./ArtifactRow.tsx";
export type { ArtifactRowProps, ArtifactGroupProps, ArtifactLike, ArtifactKind, ArtifactKindSpec, ArtifactChange, ArtifactProducer } from "./ArtifactRow.tsx";
export { ArtifactPreview, prettyJson } from "./ArtifactPreview.tsx";
export { FileGallery, FileViewer } from "./FileGallery.tsx";
export type { FileGalleryProps, FileViewerProps, GalleryFile, FileVersion } from "./FileGallery.tsx";
export type { ArtifactPreviewProps } from "./ArtifactPreview.tsx";
export { ChatEvent, summarizeEventData, eventDetail, eventHasDetail, EVENT_SUMMARY_PAIRS } from "./ChatEvent.tsx";
export type { ChatEventProps } from "./ChatEvent.tsx";
export { ChatNotice } from "./ChatNotice.tsx";
export type { ChatNoticeProps, ChatNoticeKind } from "./ChatNotice.tsx";
export { ChatProgress, progressFraction } from "./ChatProgress.tsx";
export type { ChatProgressProps } from "./ChatProgress.tsx";
export { StepList, StepRow } from "./StepList.tsx";
export type { StepListProps, StepRowProps } from "./StepList.tsx";
export { SettingsLayout, SettingsHeader, SettingsNote, SettingsExplainer, SettingsSection, SettingRow, SettingSource, SettingFields, SettingField, SettingsDisclosure, SettingsMeta, TextButton, Switch } from "./Settings.tsx";
export type { SettingsLayoutProps, SettingsNavItem, SettingRowProps, SettingSourceProps, SwitchProps } from "./Settings.tsx";
export { PromptHistory } from "./PromptHistory.tsx";
export type { PromptHistoryProps, PromptHistoryVersion } from "./PromptHistory.tsx";
export { EpicCard, EpicRow, EpicProgress, EpicPullRequests } from "./EpicCard.tsx";
export type { EpicCardProps, EpicRowProps, EpicSummary, EpicLanes } from "./EpicCard.tsx";
export { ScreenHeader, Segmented } from "./ScreenHeader.tsx";
export type { ScreenHeaderProps, SegmentedProps } from "./ScreenHeader.tsx";
export { WaitingGroup, WaitingRow } from "./WaitingList.tsx";
export type { WaitingGroupProps, WaitingRowProps } from "./WaitingList.tsx";
export { PullRequestPanel } from "./PullRequestPanel.tsx";
export type { FactKind, PullRequestPanelProps } from "./PullRequestPanel.tsx";
export { Timeline, TimelineItem } from "./Timeline.tsx";
export type { TimelineProps, TimelineItemProps } from "./Timeline.tsx";
export { SessionList, SessionItem } from "./SessionList.tsx";
export { DiffStat } from "./DiffStat.tsx";
export type { DiffStatProps } from "./DiffStat.tsx";
export { SessionRail, SessionRailBlock, SessionFacts, ToolUsage, ChangedFiles } from "./SessionRail.tsx";
export type { ChangedFile, ToolCount } from "./SessionRail.tsx";
export type { SessionListProps, SessionItemProps } from "./SessionList.tsx";
export { ServerStateDot, ServerStateMark } from "./ServerStateMark.tsx";
export type { ServerStateDotProps, ServerStateMarkProps } from "./ServerStateMark.tsx";
export { AutostartMark, ServerList, ServerRecipeRow, ServerRow, ServersPanel, ServersRecipesPreview, ServersRunLine, ServersTabTip, ShortId, TerminalLink } from "./ServerRow.tsx";
export type { AutostartMarkProps, ServerListProps, ServerLogs, ServerRecipeRowProps, ServerRowProps, ServersPanelProps, ServersRecipesPreviewProps, ServersRunLineProps, ServersTabTipProps } from "./ServerRow.tsx";
export { PreviewAlsoRunning, PreviewStages, ServersMoved, PREVIEW_STAGES } from "./PreviewStages.tsx";
export type { PreviewAlsoRunningProps, PreviewStagesProps, ServersMovedProps } from "./PreviewStages.tsx";
export { ServersSummary, ServersSummaryRow } from "./ServersSummary.tsx";
export type { ServersSummaryProps, ServersSummaryRowProps } from "./ServersSummary.tsx";
export { ServerRecipeDialog, ServerRecipeTable, EnvVarRows, ServerUrlPreview } from "./ServerRecipe.tsx";
export type { EnvVarRowsProps, RecipeEnvVar, ServerRecipeDialogProps, ServerRecipeDraft, ServerRecipeTableProps, ServerUrlPreviewProps } from "./ServerRecipe.tsx";
export { HostChips } from "./HostChips.tsx";
export type { HostChipsProps } from "./HostChips.tsx";
export { SearchResultList, SearchResultRow } from "./SearchResultRow.tsx";
export type { SearchResultRowProps } from "./SearchResultRow.tsx";
export { RefLead } from "./RefLead.tsx";
export type { RefLeadProps, RefLeadSpec, RefType } from "./RefLead.tsx";
export { RemovableList } from "./RemovableList.tsx";
export type { RemovableItem, RemovableListProps } from "./RemovableList.tsx";
export { SearchPicker } from "./SearchPicker.tsx";
export type { SearchPickerProps } from "./SearchPicker.tsx";
export { FitBar, MachineChip, MachineTip, ProportionBar, ReservedSwatch, UsedBy } from "./Machines.tsx";
export type { FitBarProps, MachineChipProps, ProportionBarProps, ProportionSegment } from "./Machines.tsx";
export { CodeEditor } from "./CodeEditor.tsx";
export type { CodeEditorProps, CodeDiagnostic, CodeCompletion, CodeCompletionContext } from "./CodeEditor.tsx";
export { ImagePicker, ImageMark, ImageStatusBadge } from "./ImagePicker.tsx";
export type { ImagePickerProps, ImageChoiceView } from "./ImagePicker.tsx";
export { BuildQueueStrip, BuildStages, ImageState, ImageHistory } from "./Images.tsx";
export type { BuildQueueStripProps, BuildStage, BuildStageState, ImageStateKind, ImageHistoryProps, ImageHistoryVersion } from "./Images.tsx";
